name: Backend build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 13
        uses: actions/setup-java@v1
        with:
          java-version: 13.0.2
      - name: Build with Maven
        run: mvn clean package
      - name: Login to gcloud registry
        id: gcloud
        uses: elgohr/gcloud-login-action@master
        with:
          account_key: ${{ secrets.GCLOUD_AUTH }}
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: supermarket/backend
          tag: "latest"
          username: ${{ steps.gcloud.outputs.username }}
          password: ${{ steps.gcloud.outputs.password }}
          registry: gcr.io/genial-analyzer-268419
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '281.0.0'
          service_account_email: "highvoltage@genial-analyzer-268419.iam.gserviceaccount.com"
          service_account_key: ${{ secrets.GCLOUD_AUTH_BASE64 }}
          export_default_credentials: true
      - name: 'Install Helm 3'
        run: |
          gcloud container clusters get-credentials my-gke-cluster --project=genial-analyzer-268419 --zone=europe-west3
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
