name: Backend build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 13
        uses: actions/setup-java@v1
        with:
          java-version: 13.0.2
      - name: Build with Maven
        run: mvn clean package
      - name: Cloud Run branch deployment
        uses: schliflo/action-cloud-run@1.0.0
        with:
          # Directory where the Dockerfile is to be found
          working_directory: .
          # Cloud run service name
          service_name: highvoltage
          # GCP service key with storage and run permissions
          key: ${{ secrets.GCLOUD_AUTH }}
          # GCP project
          project: genial-analyzer-268419
          region: europe-west3